name: 'Solution Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Everything:
    runs-on: windows-latest  # Window application cannot be run on other OS

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.x'
        dotnet-quality: 'preview'

    - name: Build AM
      run: dotnet build Sources/AngouriMath/AngouriMath/AngouriMath.csproj

    - name: Build FSharp
      run: dotnet build Sources/Wrappers/AngouriMath.FSharp/AngouriMath.FSharp.fsproj

    - name: Build Interactive
      run: dotnet build Sources/Wrappers/AngouriMath.Interactive/AngouriMath.Interactive.fsproj

    - name: Build Analyzers
      run: dotnet build Sources/Analyzers/Analyzers/Analyzers.csproj

    - name: Build Utils
      run: dotnet build Sources/Utils/Utils/Utils.csproj
